NAME = 'web1'  
 IP = "192.168.1.12" # o bilgisayardan bu localhost agına baglanıp uygulamaya erişiyioruz

Vagrant.configure("2") do |config|  
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = NAME
  config.vm.network "public_network", ip: IP

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", '2048']
  end
end